---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm

spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      name: mytemplate
      labels:
        app: zomato
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80


